service: sootam-login
frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  runtime: nodejs18.x
  region: ap-northeast-2
  httpApi:
    cors:
      allowCredentials: true
      allowedOrigins:
        - http://localhost:8080
        - http://sootam.com
      allowedHeaders:
        - Content-Type
        - Authorization
        - Access-Control-Allow-Headers
        - Access-Control-Allow-Origin
        - Access-Control-Allow-Methods
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE

functions:
  login:
    handler: index.handler
    events:
      - httpApi:
          path: /signUp
          method: post
      - httpApi:
          path: /signIn
          method: post
      - httpApi:
          path: /socialLogin
          method: get

plugins:
  - serverless-latest-layer-version
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001

package:
  patterns:
    - "!node_modules/**"
    - "!gitignore"
    - "!git/**"
